//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/SwitchInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SwitchInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SwitchInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SwitchInputActions"",
    ""maps"": [
        {
            ""name"": ""SwitchMap"",
            ""id"": ""dbe55d6e-bd07-45e2-9c64-a3446a18ab9e"",
            ""actions"": [
                {
                    ""name"": ""Switch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ef973db8-efa6-4c03-b4a0-12c599527795"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""30e4bc55-2650-4e8f-8d05-ce170ac765d6"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SwitchMap
        m_SwitchMap = asset.FindActionMap("SwitchMap", throwIfNotFound: true);
        m_SwitchMap_Switch = m_SwitchMap.FindAction("Switch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SwitchMap
    private readonly InputActionMap m_SwitchMap;
    private List<ISwitchMapActions> m_SwitchMapActionsCallbackInterfaces = new List<ISwitchMapActions>();
    private readonly InputAction m_SwitchMap_Switch;
    public struct SwitchMapActions
    {
        private @SwitchInputActions m_Wrapper;
        public SwitchMapActions(@SwitchInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Switch => m_Wrapper.m_SwitchMap_Switch;
        public InputActionMap Get() { return m_Wrapper.m_SwitchMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SwitchMapActions set) { return set.Get(); }
        public void AddCallbacks(ISwitchMapActions instance)
        {
            if (instance == null || m_Wrapper.m_SwitchMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SwitchMapActionsCallbackInterfaces.Add(instance);
            @Switch.started += instance.OnSwitch;
            @Switch.performed += instance.OnSwitch;
            @Switch.canceled += instance.OnSwitch;
        }

        private void UnregisterCallbacks(ISwitchMapActions instance)
        {
            @Switch.started -= instance.OnSwitch;
            @Switch.performed -= instance.OnSwitch;
            @Switch.canceled -= instance.OnSwitch;
        }

        public void RemoveCallbacks(ISwitchMapActions instance)
        {
            if (m_Wrapper.m_SwitchMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISwitchMapActions instance)
        {
            foreach (var item in m_Wrapper.m_SwitchMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SwitchMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SwitchMapActions @SwitchMap => new SwitchMapActions(this);
    public interface ISwitchMapActions
    {
        void OnSwitch(InputAction.CallbackContext context);
    }
}
